// <auto-generated />
using ETA.Integrator.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ETA.Integrator.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250416122805_InsertingConstants-SettingsSteps")]
    partial class InsertingConstantsSettingsSteps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ETA.Integrator.Server.Entities.SettingsStep", b =>
                {
                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Order");

                    b.ToTable("SettingsSteps");

                    b.HasData(
                        new
                        {
                            Order = 1,
                            Name = "connection-settings"
                        },
                        new
                        {
                            Order = 2,
                            Name = "issuer-settings"
                        });
                });

            modelBuilder.Entity("ETA.Integrator.Server.Entities.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Test1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Test2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
